// Generate contracts/pool/src/vk.rs from the snarkjs verification key, so the
// proving key and the on-chain verifying key can never drift.
//
//   npm run gen:vk      (tsx scripts/gen-vk.ts)
//
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { vkToSorobanBytes, type SnarkVerificationKey } from '../lib/src/groth16.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const VKEY = path.join(ROOT, 'circuits/build/aid_claim.vkey.json');
const OUT = path.join(ROOT, 'contracts/pool/src/vk.rs');

function rustArray(bytes: Uint8Array): string {
  const items = Array.from(bytes, (b) => '0x' + b.toString(16).padStart(2, '0'));
  // wrap at 12 per line for readability
  const lines: string[] = [];
  for (let i = 0; i < items.length; i += 12) {
    lines.push('    ' + items.slice(i, i + 12).join(', ') + ',');
  }
  return '[\n' + lines.join('\n') + '\n]';
}

function main(): void {
  if (!fs.existsSync(VKEY)) {
    throw new Error(`missing ${VKEY} — run "npm run circuit:build" first`);
  }
  const vk = JSON.parse(fs.readFileSync(VKEY, 'utf8')) as SnarkVerificationKey;
  const s = vkToSorobanBytes(vk);

  const icEntries = s.ic
    .map((p) => '    ' + rustArray(p).replace(/\n/g, '\n    '))
    .join(',\n');

  const out = `// AUTO-GENERATED by scripts/gen-vk.ts from circuits/build/aid_claim.vkey.json.
// Do not edit by hand. Run \`npm run gen:vk\` after rebuilding the circuit.
#![allow(clippy::all)]

/// Number of public inputs (circuit public signals).
pub const NUM_PUBLIC: usize = ${s.nPublic};

pub const VK_ALPHA: [u8; 64] = ${rustArray(s.alpha)};

pub const VK_BETA: [u8; 128] = ${rustArray(s.beta)};

pub const VK_GAMMA: [u8; 128] = ${rustArray(s.gamma)};

pub const VK_DELTA: [u8; 128] = ${rustArray(s.delta)};

/// IC has NUM_PUBLIC + 1 points.
pub const VK_IC: [[u8; 64]; ${s.ic.length}] = [
${icEntries}
];
`;

  fs.writeFileSync(OUT, out);
  console.log(`✓ wrote ${path.relative(ROOT, OUT)} (nPublic=${s.nPublic}, IC=${s.ic.length})`);
}

main();
